//! Every recipe, gathered under its own name, with a worked example beside each.
//!
//! **`S-23` made this view and `R-7` gave it the half that can be checked.** The release
//! states a recipe across seven columns and many rows, one line per ingredient or result,
//! with the name written only on its first. That is the right shape for a table and the wrong
//! one for answering *what does `deploy ark` do*. This is the same rows with the recipe as the
//! unit.
//!
//! **The rule is what an example is checked against, and the example is what can be checked.**
//! `P-330`: *putting them beside each other is what stops one drifting from the other.*
//!
//! # Why this moved out of `prototypes/kinds`
//!
//! It was generated there, from the release alone, and that was right while the file held only
//! what the release states. **`R-7` needs the game**: an example is *generated by running it*,
//! and `prototypes/kinds` depends on nothing and must go on depending on nothing -
//! `docs/architecture.md` lists its dependencies as **none**, and the whole value of the
//! two-copy comparison it does is that it shares no code with the model.
//!
//! **So the generator moved and the comparison stayed.** `kinds::recipes_table` still holds
//! the crate's own copy of the Recipes table against the document, which is `S-4` and is
//! untouched. What moved is the rendering, which is not a second copy of anything.

use crate::worked;

/// The recipes, as markdown, with a worked example under each.
pub fn recipes(document: &str) -> String {
    let mut out = String::from("# Recipes\n\n");
    out.push_str(
        "**Generated. Do not edit.** `cargo run -p game-console --bin dump-state`, or \
         `scripts/dump-state.sh`.\n\n",
    );
    out.push_str(
        "Every recipe the release declares, with its own lines gathered under it. The release \
         states\nthese across seven columns, one row per line and the name written only on \
         the first - which\nis the right shape for a table and the wrong one for answering \
         *what does this recipe do*.\n\n",
    );
    out.push_str(
        "**Beside each rule is a worked example** - a state, the command that fires the \
         recipe, and\nthe state after - in the notation `scenario/expected/play.4x` uses, \
         holding only what that\nrecipe touched. Every one is a real command run against a \
         real state: `R-7`.\n\n",
    );

    let rows = body_under(document, "## Recipes");
    let gathered = gather(&rows);
    let runs: Vec<worked::Run> = worked::examples().iter().map(worked::run).collect();
    out.push_str(&format!(
        "{} recipes, {} lines between them, {} worked examples.\n",
        gathered.len(),
        rows.len(),
        runs.len()
    ));

    for recipe in &gathered {
        out.push_str(&format!("\n## {}\n\n", recipe.name));
        out.push_str(&format!("Run by the **{}**.\n\n", recipe.owner));
        for (role, said) in &recipe.lines {
            out.push_str(&format!("- **{role}** {said}\n"));
        }

        // **An example belongs to a recipe or is shared with others** - `R-7`, as `P-332`
        // settled it: the world's six are shown once, together, on `{end-turn}`, because no
        // command fires one of them alone and four cannot act alone at all.
        let mine: Vec<&worked::Run> = runs
            .iter()
            .filter(|run| run.recipe == recipe.name || run.also.contains(&recipe.name.as_str()))
            .collect();
        if mine.is_empty() {
            // **Said rather than left blank, and it says which kind of absence it is.** A
            // heading with no example under it, in a file where every other has one, reads as
            // one nobody reached. `age` is not unreached: the model has no `keeps` and
            // discards all food at every ending, so nothing ages and an example would have to
            // be drawn. `C-61`, and `tests/worked.rs` fails if a *second* recipe joins it.
            out.push_str(
                "\n*No worked example, because the model does not implement this: it has no \
                 `keeps`, and discards all food at every ending, so nothing ages. Found by \
                 building the others - `C-61`.*\n",
            );
            continue;
        }
        for run in mine {
            out.push_str("\n### An example\n\n");
            let shared: Vec<&str> = std::iter::once(run.recipe)
                .chain(run.also.iter().copied())
                .filter(|named| *named != recipe.name)
                .collect();
            if !shared.is_empty() {
                // **Said, because one firing under six headings is a fact about the game.**
                // A reader meeting the same before and after under `spoil` and under `age`
                // should be told they are one ending rather than left to notice.
                out.push_str(&format!(
                    "**One ending, six recipes.** This same firing is the example for {} as \
                     well - no command fires one of the world's alone.\n\n",
                    shared.join(", ")
                ));
            }
            if let Some(case) = run.case {
                out.push_str(&format!("{case}.\n\n"));
            }
            out.push_str(&format!("Before:\n\n```\n{}```\n\n", run.before));
            out.push_str(&format!("`{}`\n\n", run.command));
            out.push_str(&format!("After:\n\n```\n{}```\n", run.after));
        }
    }
    out
}

/// One recipe, with the lines that belong to it.
pub struct Gathered {
    pub name: String,
    /// Whose recipe it is - the release's **Owner** column.
    pub owner: String,
    /// Each line's role and what it says, in the order the table gives them.
    pub lines: Vec<(String, String)>,
}

/// The rows of one recipe, with its name carried down from the row that has it.
///
/// **The name is on the first row only**, which is what makes the table hard to read and is
/// also the one thing a gatherer has to get right: a recipe whose name failed to carry would
/// silently absorb the next recipe's lines, and the result would look like a longer recipe
/// rather than like an error.
fn gather(rows: &[Vec<String>]) -> Vec<Gathered> {
    let mut out: Vec<Gathered> = Vec::new();
    for row in rows {
        let name = plain(row.first().map(String::as_str).unwrap_or_default());
        let owner = row.get(1).cloned().unwrap_or_default();
        if !name.is_empty() {
            out.push(Gathered {
                name,
                owner,
                lines: Vec::new(),
            });
        }
        let Some(recipe) = out.last_mut() else {
            continue; // a line before any name: the table's shape has changed
        };
        let role = row.get(2).cloned().unwrap_or_default();
        if role.is_empty() {
            continue;
        }
        recipe.lines.push((role, said(row)));
    }
    out
}

/// One line of a recipe, as a sentence rather than as cells.
fn said(row: &[String]) -> String {
    let quantity = row.get(3).cloned().unwrap_or_default();
    let kind = row.get(4).cloned().unwrap_or_default();
    let traits = row.get(5).cloned().unwrap_or_default();
    let place = row.get(6).cloned().unwrap_or_default();

    // **A quantity is not always a number.** `work` produces *`$where`'s density for that
    // resource* of a *resource*, and writing quantity-then-kind gives *...for that resource
    // resource*. When the quantity is not a bare count the kind leads instead, which reads
    // as the release means it: what is produced, then how much.
    let counted = quantity.chars().all(|c| c.is_ascii_digit()) && !quantity.is_empty();
    let mut out = if counted {
        format!("{quantity} {kind}")
    } else {
        format!("{kind} — {quantity}")
    };
    if !traits.is_empty() {
        out.push_str(&format!(", {traits}"));
    }
    if !place.is_empty() {
        out.push_str(&format!(", in {place}"));
    }
    out
}

/// Every body row under a heading, as trimmed cells.
///
/// **Parsed to cells rather than matched as text**, for the reason `CLAUDE.md` gives: the
/// padder owns the column widths and rewrites them whenever anything else in the file
/// changes, so splitting on `|` is pad-proof where matching a row's bytes is not.
fn body_under(document: &str, heading: &str) -> Vec<Vec<String>> {
    let mut rows = Vec::new();
    let mut inside = false;
    let mut after_separator = false;
    for line in document.lines() {
        if line.starts_with("## ") {
            if inside {
                break;
            }
            inside = line.trim() == heading;
            continue;
        }
        let line = line.trim();
        if !inside || !line.starts_with('|') {
            continue;
        }
        let cells: Vec<String> = line
            .trim_matches('|')
            .split('|')
            .map(|cell| cell.trim().to_string())
            .collect();
        if cells.iter().all(|cell| cell.chars().all(|c| c == '-')) {
            after_separator = true;
            rows.clear();
            continue;
        }
        if !after_separator {
            continue;
        }
        rows.push(cells);
    }
    rows
}

/// A name as the tables write it, with the emphasis markers taken off.
fn plain(cell: &str) -> String {
    cell.trim().trim_matches('*').trim().to_string()
}
