//! A worked example beside each recipe: a state, the command, and the state after.
//!
//! **`R-7`, and it is a capability rather than a rule** - `P-330`. Sean vets it by reading
//! `reports/recipes.md` and deriving the after from the rule and the before by hand.
//!
//! > **Vetted when** - `reports/recipes.md` shows, beside each recipe's rule, a state before
//! > it fires, the command that fires it, and the state after - **in the same notation as the
//! > scenario's expected data**, holding only what that recipe touches, and generated by
//! > running it. I can derive the after from the rule and the before by hand, and a recipe
//! > whose quantity is an expression shows one example for each way the expression turns out
//!
//! # Generated by running it, never drawn
//!
//! `P-330`'s own words: *a written example can show behaviour the code does not have, and
//! this repository has produced three of those in one week - a requirement no kind could
//! satisfy, quantities the model never computed, and a value the release never named. All
//! three sat in artifacts whose purpose was hand-derivation*, which is what this is.
//!
//! So every example here is a real command run against a real state, and both states are
//! rendered by [`crate::state`] - the same writer the scenario's expected data uses, which is
//! what *the same notation* means.
//!
//! # Only what the recipe touches, derived rather than declared
//!
//! A game has twelve territories and twelve orbits whatever the recipe does, and printing all
//! of them would bury the four lines that matter. **So the two states are compared and only
//! the places that changed are shown.** That is a fact about the run rather than a claim
//! about the recipe: a recipe that touched something unexpected would show it, which is the
//! direction that matters.

use game_model::containment::{Entry, tree};
use game_model::{Game, Resource, TerritoryId};

/// One example: what to fire it in, what fires it, and why this case.
pub struct Example {
    /// The recipe, spelled as `releases/first-release.md` spells it.
    pub recipe: &'static str,
    /// The other recipes this same firing shows, spelled the same way.
    ///
    /// **`R-7`, as `P-332` settled it**: *the world's recipes are shown once, together, on
    /// `{end-turn}`, because no command fires one of them alone and four of them cannot act
    /// alone at all.* So one example belongs under six headings, and this is the list the
    /// report and the coverage check both read.
    pub also: &'static [&'static str],
    /// The command that fires it, as a player would type it.
    pub command: &'static str,
    /// Which case this is, for a recipe whose quantity is an expression.
    ///
    /// **`P-330` asks for one example per way the expression turns out**, and `grow` bends at
    /// three points. `None` means the recipe has one behaviour and one example shows it.
    pub case: Option<&'static str>,
    /// The state to fire it in.
    pub before: fn() -> Game,
}

/// A state, the command, and the state after - the three things `R-7` asks for.
pub struct Run {
    pub recipe: &'static str,
    pub also: &'static [&'static str],
    pub case: Option<&'static str>,
    pub command: &'static str,
    pub before: String,
    pub after: String,
}

/// Fire one example and render what it touched.
///
/// **The command goes through the console**, so what is shown is what a player typing that
/// line would get. A refusal is a panic here rather than a rendered example: an example of a
/// command that does not run is not an example of the recipe.
pub fn run(example: &Example) -> Run {
    let mut session = crate::Session::new();
    session.game = (example.before)();
    let before = tree(&session.game);

    session
        .run(example.command, &crate::NoLibrary)
        .unwrap_or_else(|why| {
            panic!(
                "`{}` is the example for `{}` and it was refused: {why}",
                example.command, example.recipe
            )
        });
    let after = tree(&session.game);

    let touched = changed(&before, &after);
    Run {
        recipe: example.recipe,
        also: example.also,
        case: example.case,
        command: example.command,
        before: restricted(&before, &touched),
        after: restricted(&after, &touched),
    }
}

/// The places whose contents differ between two states, by their written description.
///
/// **Matched on the description rather than on position**, because a place is identified by
/// what it says it is - `spec/console.md` - and the two trees sort independently.
fn changed(before: &Entry, after: &Entry) -> Vec<String> {
    let mut touched = Vec::new();
    for place in before.contents.iter().chain(after.contents.iter()) {
        let named = place.description.written();
        if touched.contains(&named) {
            continue;
        }
        let in_before = before
            .contents
            .iter()
            .find(|entry| entry.description == place.description);
        let in_after = after
            .contents
            .iter()
            .find(|entry| entry.description == place.description);
        let same = match (in_before, in_after) {
            (Some(one), Some(other)) => one.contents == other.contents,
            _ => false,
        };
        if !same {
            touched.push(named);
        }
    }
    touched.sort();
    touched
}

/// A state holding only the named places, in the notation the expected data uses.
fn restricted(state: &Entry, places: &[String]) -> String {
    let mut kept = state.clone();
    kept.contents
        .retain(|entry| places.contains(&entry.description.written()));
    crate::state::written(&kept)
}

/// A territory holding what the example needs, and a second one where a move needs somewhere
/// to go.
///
/// **Built in the model rather than by running commands.** How the state was reached is not
/// part of the example - `R-7` asks for a state, a command and a state - and a setup written
/// as thirty commands would be a second scenario to keep correct.
fn founded(offers: &[(Resource, u32, u32)], holds: &[(game_model::thing::Kind, u32)]) -> Game {
    let mut game = ground(offers);
    let place = &mut game.territories[0];
    place.set_garrison(Some(game_model::territory::Garrison { force: 0 }));
    // **A citizen, because control is derived from one being there** -
    // `releases/first-release.md` -> *Traits*, and `S-19` made it derived so nothing could
    // leave it wrong. A garrison alone is ground nobody holds, and every player recipe
    // requires the territory.
    if !holds
        .iter()
        .any(|(kind, _)| *kind == game_model::thing::Kind::Citizen)
    {
        place.put(game_model::thing::Kind::Citizen, 1);
    }
    for (kind, count) in holds {
        place.put(*kind, *count);
    }
    game
}

/// Two territories that touch, the first held and the second whatever the example needs.
fn beside(second_is_held: bool) -> Game {
    let mut game = founded(&[], &[]);
    let mut other = game_model::Territory::empty(TerritoryId(2), game_model::Biome::Grassland);
    if second_is_held {
        other.set_garrison(Some(game_model::territory::Garrison { force: 0 }));
        other.put(game_model::thing::Kind::Citizen, 1);
    }
    game.territories.push(other);
    game.adjacency = vec![vec![TerritoryId(2)], vec![TerritoryId(1)]];
    game
}

/// The examples, one per recipe and one per way an expression turns out.
///
/// **A recipe with no example here fails `tests/worked.rs`**, which reads the release's own
/// Recipes table and asks for one. So a recipe added to the release cannot quietly arrive
/// without a worked example, which is the only version of this that stays true.
pub fn examples() -> Vec<Example> {
    use game_model::thing::Kind;
    vec![
        Example {
            also: &[],
            recipe: "deploy ark",
            command: "{deploy-ark territory:1}",
            case: None,
            before: || {
                let mut game = ground(&[(Resource::Food, 3, 4), (Resource::Metal, 3, 4)]);
                game.units.push(game_model::Unit::new(
                    game_model::UnitId(1),
                    game_model::UnitKind::Ark,
                    TerritoryId(1),
                ));
                game
            },
        },
        Example {
            also: &[],
            recipe: "create labor",
            command: "{create-labor territory:1}",
            case: None,
            before: || founded(&[], &[(Kind::Citizen, 1)]),
        },
        Example {
            also: &[],
            recipe: "work",
            command: "{work territory:1 resource:food}",
            case: Some("the density is what one extractor yields, so four food from a `3 x 4`"),
            before: || {
                let mut game = founded(&[(Resource::Food, 3, 4)], &[(Kind::Labor, 1)]);
                game.territories[0].add_extractor(Resource::Food);
                game.territories[0].add_store(Resource::Food);
                game
            },
        },
        Example {
            also: &[],
            recipe: "build extractor",
            command: "{build-extractor territory:1 resource:metal}",
            case: None,
            before: || {
                founded(
                    &[(Resource::Metal, 3, 4)],
                    &[(Kind::Labor, 1), (Kind::Metal, 1)],
                )
            },
        },
        Example {
            also: &[],
            recipe: "build store",
            command: "{build-store territory:1 resource:metal}",
            case: None,
            before: || {
                let mut game = founded(
                    &[(Resource::Metal, 3, 4)],
                    &[(Kind::Labor, 1), (Kind::Metal, 1)],
                );
                game.territories[0].add_extractor(Resource::Metal);
                game
            },
        },
        Example {
            also: &[],
            recipe: "build yard",
            command: "{build-yard territory:1}",
            case: None,
            before: || founded(&[], &[(Kind::Labor, 1), (Kind::Metal, 15)]),
        },
        Example {
            also: &[],
            recipe: "produce pioneer",
            command: "{produce-pioneer territory:1}",
            case: None,
            before: || {
                founded(
                    &[],
                    &[(Kind::Citizen, 2), (Kind::Metal, 3), (Kind::Energy, 6)],
                )
            },
        },
        Example {
            also: &[],
            recipe: "move",
            command: "{move unit:pioneer territory:2}",
            case: Some("moving spends one fuel and leaves the unit not ready"),
            before: || {
                let mut game = beside(true);
                let mut unit = game_model::Unit::new(
                    game_model::UnitId(1),
                    game_model::UnitKind::Pioneer,
                    TerritoryId(1),
                );
                unit.location = game_model::Location::On(TerritoryId(1));
                game.units.push(unit);
                game
            },
        },
        Example {
            also: &[],
            recipe: "found by land",
            command: "{found-by-land territory:2}",
            case: Some("the pioneer is consumed and the ground it takes is furnished"),
            // **The pioneer stands on the ground it founds - `S-76`.** It used to be placed
            // on territory 1 and reach across, because founding was a move and a founding in
            // one act. It is placed on territory 2 now, which is what a worked example of
            // this recipe has to show: the crossing is `move`'s example, one entry above.
            before: || {
                let mut game = beside(false);
                game.territories[1].deposits.insert(
                    Resource::Food,
                    game_model::Deposit {
                        capacity: 3,
                        density: 4,
                    },
                );
                game.territories[1].deposits.insert(
                    Resource::Metal,
                    game_model::Deposit {
                        capacity: 3,
                        density: 4,
                    },
                );
                let mut unit = game_model::Unit::new(
                    game_model::UnitId(1),
                    game_model::UnitKind::Pioneer,
                    TerritoryId(2),
                );
                unit.location = game_model::Location::On(TerritoryId(2));
                game.units.push(unit);
                game
            },
        },
        // **The world's, shown once on one `{end-turn}`** - `R-7`, as `P-332` settled it.
        //
        // **Ten now rather than six**, which is the saturating rewrite: `grow` is gone, and
        // `bear`, `breed` and `renew` are the rule it became; the two capacity clamps became
        // `stow` and `discard`. `P-379` states the order they fire in.
        //
        // **Two territories, because growing and perishing cannot both happen in one.** Both
        // are decided from the same food: breeding needs food left after upkeep and perishing
        // needs upkeep to have gone unpaid, and one territory's food cannot be both. Upkeep is
        // per territory, so a planet can do both in one ending and a territory cannot.
        Example {
            also: &[
                "bear", "breed", "renew", "perish", "age", "spoil", "stow", "discard", "refresh",
            ],
            recipe: "upkeep",
            command: "{end-turn}",
            case: Some(
                "the world's ten in one ending, in the release's order, and the way the \
                 population settles when **the food is the lesser**. Territory 1 has three \
                 food for two citizens: `upkeep` feeds both, `bear` turns each of them spent \
                 and leaves two fertility, and `breed` fires **once** rather than twice - \
                 there is one food left and each new citizen costs one. `renew` makes both \
                 parents fertile again. Territory 2 has no food, so its citizen goes unpaid, \
                 `breed` cannot fire there at all, and `perish` takes it. What food is left \
                 expires, the fertility nobody bred with is discarded, and the worked \
                 extractor is ready again. **The pioneer in territory 2 is untouched**, \
                 because nothing but a citizen eats - `P-339`. This note used to say it \
                 starved and that the file could not show it, which was true of an older rule \
                 and of a `usable` trait the release never declared; `P-367` removed the last \
                 thing that set that trait, so there is no state a unit can be in now that an \
                 artifact cannot show. `C-62`",
            ),
            before: || {
                let mut game = founded(&[(Resource::Food, 3, 4)], &[(Kind::Citizen, 2)]);
                {
                    let place = &mut game.territories[0];
                    place.add_store(Resource::Food);
                    // **Three, so the surplus is the lesser - `S-79`.** It was four, which
                    // left a surplus of two against two citizens: a tie, which demonstrates
                    // neither way the expression turns out. Two eat, one is left over, and
                    // that one surplus is what `grow` takes.
                    place.add(Resource::Food, 3);

                    // A worked extractor, so `refresh` has something to make ready again.
                    place.add_extractor(Resource::Food);
                    place.exhaust_extractor(0);
                }

                // A second territory with a pioneer and nothing to feed it.
                let mut hungry =
                    game_model::Territory::empty(TerritoryId(2), game_model::Biome::Grassland);
                hungry.set_garrison(Some(game_model::territory::Garrison { force: 0 }));
                hungry.put(Kind::Citizen, 1);
                game.territories.push(hungry);
                game.adjacency = vec![vec![TerritoryId(2)], vec![TerritoryId(1)]];

                let mut starving = game_model::Unit::new(
                    game_model::UnitId(1),
                    game_model::UnitKind::Pioneer,
                    TerritoryId(2),
                );
                starving.location = game_model::Location::On(TerritoryId(2));
                game.units.push(starving);
                game
            },
        },
        // **The other way the population settles, and it is `breed`'s bound rather than an
        // expression's.** This was `grow`'s second case: `R-7` asks for one example per way
        // an expression turns out, and `grow` consumed *the lesser of the surplus food and
        // the citizens here*. **The expression is gone and the two outcomes are not** - what
        // used to be one word bounding two things is now two recipes bounding one each, and
        // each deserves showing.
        //
        // The ending above is the way where the food runs out first. This is the way where
        // the citizens do: `bear` can only turn each citizen spent once, so however much food
        // is left, `breed` has no more fertility to spend.
        //
        // **`also` is empty deliberately.** This firing is an `{end-turn}` like any other and
        // the world's other recipes act in it, but they are shown once together above -
        // `P-332` - and listing them here would give nine recipes a second example to answer
        // a question only `breed` asks.
        //
        // The model's own tests name these two: *two spare feed two new*, and *plenty still
        // only doubles*.
        Example {
            also: &[],
            recipe: "breed",
            command: "{end-turn}",
            case: Some(
                "the way the population settles when **the citizens are the lesser**. Two \
                 citizens eat two of the eight food, leaving six - but `bear` made only two \
                 fertility, one per citizen, so `breed` fires **twice** and stops, with four \
                 food it has no fertility left to spend. That is the doubling the old `grow` \
                 expression bounded in a word and the `spent` trait bounds in a rule: a \
                 population grows by at most itself, however much food there is. **The four \
                 it did not spend are gone from the state after**, and that is `age` and \
                 `spoil` rather than `breed` - food keeps for one turn, so what a territory \
                 is still holding when the turn ends expires with it",
            ),
            before: || {
                let mut game = founded(&[(Resource::Food, 3, 4)], &[(Kind::Citizen, 2)]);
                let place = &mut game.territories[0];
                place.add_store(Resource::Food);
                place.add(Resource::Food, 8);
                game
            },
        },
        Example {
            also: &[],
            recipe: "launch ark",

            command: "{launch-ark territory:1}",
            case: None,
            before: || {
                founded(
                    &[],
                    &[
                        (Kind::Citizen, 2),
                        (Kind::Metal, 3),
                        (Kind::Energy, 12),
                        (Kind::Yard, 1),
                    ],
                )
            },
        },
    ]
}

/// Ground with one resource, and nothing on it.
fn ground(offers: &[(Resource, u32, u32)]) -> Game {
    let mut game = Game::new();
    game.phase = game_model::Phase::Play;
    game.turn = 1;
    let mut place = game_model::Territory::empty(TerritoryId(1), game_model::Biome::Grassland);
    for (resource, capacity, density) in offers {
        place.deposits.insert(
            *resource,
            game_model::Deposit {
                capacity: *capacity,
                density: *density,
            },
        );
    }
    game.territories.push(place);
    game.adjacency.push(Vec::new());
    game
}
