//! A worked example beside each recipe: a state, the command, and the state after.
//!
//! **`R-7`, and it is a capability rather than a rule** - `P-330`. Sean vets it by reading
//! `reports/recipes.md` and deriving the after from the rule and the before by hand.
//!
//! > **Vetted when** - `reports/recipes.md` shows, beside each recipe's rule, a state before
//! > it fires, the command that fires it, and the state after - **in the same notation as the
//! > scenario's expected data**, holding only what that recipe touches, and generated by
//! > running it. I can derive the after from the rule and the before by hand, and a recipe
//! > whose quantity is an expression shows one example for each way the expression turns out
//!
//! # Generated by running it, never drawn
//!
//! `P-330`'s own words: *a written example can show behaviour the code does not have, and
//! this repository has produced three of those in one week - a requirement no kind could
//! satisfy, quantities the model never computed, and a value the release never named. All
//! three sat in artifacts whose purpose was hand-derivation*, which is what this is.
//!
//! So every example here is a real command run against a real state, and both states are
//! rendered by [`crate::state`] - the same writer the scenario's expected data uses, which is
//! what *the same notation* means.
//!
//! # Only what the recipe touches, derived rather than declared
//!
//! A game has twelve territories and twelve orbits whatever the recipe does, and printing all
//! of them would bury the four lines that matter. **So the two states are compared and only
//! the places that changed are shown.** That is a fact about the run rather than a claim
//! about the recipe: a recipe that touched something unexpected would show it, which is the
//! direction that matters.

use game_model::containment::{Entry, tree};
use game_model::{Game, Resource, TerritoryId};

/// One example: what to fire it in, what fires it, and why this case.
pub struct Example {
    /// The recipe, spelled as `releases/first-release.md` spells it.
    pub recipe: &'static str,
    /// The command that fires it, as a player would type it.
    pub command: &'static str,
    /// Which case this is, for a recipe whose quantity is an expression.
    ///
    /// **`P-330` asks for one example per way the expression turns out**, and `grow` bends at
    /// three points. `None` means the recipe has one behaviour and one example shows it.
    pub case: Option<&'static str>,
    /// The state to fire it in.
    pub before: fn() -> Game,
}

/// A state, the command, and the state after - the three things `R-7` asks for.
pub struct Run {
    pub recipe: &'static str,
    pub case: Option<&'static str>,
    pub command: &'static str,
    pub before: String,
    pub after: String,
}

/// Fire one example and render what it touched.
///
/// **The command goes through the console**, so what is shown is what a player typing that
/// line would get. A refusal is a panic here rather than a rendered example: an example of a
/// command that does not run is not an example of the recipe.
pub fn run(example: &Example) -> Run {
    let mut session = crate::Session::new();
    session.game = (example.before)();
    let before = tree(&session.game);

    session
        .run(example.command, &crate::NoLibrary)
        .unwrap_or_else(|why| {
            panic!(
                "`{}` is the example for `{}` and it was refused: {why}",
                example.command, example.recipe
            )
        });
    let after = tree(&session.game);

    let touched = changed(&before, &after);
    Run {
        recipe: example.recipe,
        case: example.case,
        command: example.command,
        before: restricted(&before, &touched),
        after: restricted(&after, &touched),
    }
}

/// The places whose contents differ between two states, by their written description.
///
/// **Matched on the description rather than on position**, because a place is identified by
/// what it says it is - `spec/console.md` - and the two trees sort independently.
fn changed(before: &Entry, after: &Entry) -> Vec<String> {
    let mut touched = Vec::new();
    for place in before.contents.iter().chain(after.contents.iter()) {
        let named = place.description.written();
        if touched.contains(&named) {
            continue;
        }
        let in_before = before
            .contents
            .iter()
            .find(|entry| entry.description == place.description);
        let in_after = after
            .contents
            .iter()
            .find(|entry| entry.description == place.description);
        let same = match (in_before, in_after) {
            (Some(one), Some(other)) => one.contents == other.contents,
            _ => false,
        };
        if !same {
            touched.push(named);
        }
    }
    touched.sort();
    touched
}

/// A state holding only the named places, in the notation the expected data uses.
fn restricted(state: &Entry, places: &[String]) -> String {
    let mut kept = state.clone();
    kept.contents
        .retain(|entry| places.contains(&entry.description.written()));
    crate::state::written(&kept)
}

/// A territory holding what the example needs, and a second one where a move needs somewhere
/// to go.
///
/// **Built in the model rather than by running commands.** How the state was reached is not
/// part of the example - `R-7` asks for a state, a command and a state - and a setup written
/// as thirty commands would be a second scenario to keep correct.
fn founded(offers: &[(Resource, u32, u32)], holds: &[(game_model::thing::Kind, u32)]) -> Game {
    let mut game = ground(offers);
    let place = &mut game.territories[0];
    place.set_garrison(Some(game_model::territory::Garrison {
        force: 0,
        manned: 0,
    }));
    // **A citizen, because control is derived from one being there** -
    // `releases/first-release.md` -> *Traits*, and `S-19` made it derived so nothing could
    // leave it wrong. A garrison alone is ground nobody holds, and every player recipe
    // requires the territory.
    if !holds
        .iter()
        .any(|(kind, _)| *kind == game_model::thing::Kind::Citizen)
    {
        place.put(game_model::thing::Kind::Citizen, 1);
    }
    for (kind, count) in holds {
        place.put(*kind, *count);
    }
    game
}

/// Two territories that touch, the first held and the second whatever the example needs.
fn beside(second_is_held: bool) -> Game {
    let mut game = founded(&[], &[]);
    let mut other = game_model::Territory::empty(TerritoryId(2), game_model::Biome::Grassland);
    if second_is_held {
        other.set_garrison(Some(game_model::territory::Garrison {
            force: 0,
            manned: 0,
        }));
        other.put(game_model::thing::Kind::Citizen, 1);
    }
    game.territories.push(other);
    game.adjacency = vec![vec![TerritoryId(2)], vec![TerritoryId(1)]];
    game
}

/// The examples, one per recipe and one per way an expression turns out.
///
/// **A recipe with no example here fails `tests/worked.rs`**, which reads the release's own
/// Recipes table and asks for one. So a recipe added to the release cannot quietly arrive
/// without a worked example, which is the only version of this that stays true.
pub fn examples() -> Vec<Example> {
    use game_model::thing::Kind;
    vec![
        Example {
            recipe: "deploy ark",
            command: "{deploy-ark territory:1}",
            case: None,
            before: || {
                let mut game = ground(&[(Resource::Food, 3, 4), (Resource::Metal, 3, 4)]);
                game.units.push(game_model::Unit::new(
                    game_model::UnitId(1),
                    game_model::UnitKind::Ark,
                    TerritoryId(1),
                ));
                game
            },
        },
        Example {
            recipe: "create labor",
            command: "{create-labor territory:1}",
            case: None,
            before: || founded(&[], &[(Kind::Citizen, 1)]),
        },
        Example {
            recipe: "work",
            command: "{work territory:1 resource:food}",
            case: Some("the density is what one extractor yields, so four food from a `3 x 4`"),
            before: || {
                let mut game = founded(&[(Resource::Food, 3, 4)], &[(Kind::Labor, 1)]);
                game.territories[0].add_extractor(Resource::Food);
                game.territories[0].add_store(Resource::Food);
                game
            },
        },
        Example {
            recipe: "build extractor",
            command: "{build-extractor territory:1 resource:metal}",
            case: None,
            before: || {
                founded(
                    &[(Resource::Metal, 3, 4)],
                    &[(Kind::Labor, 1), (Kind::Metal, 1)],
                )
            },
        },
        Example {
            recipe: "build store",
            command: "{build-store territory:1 resource:metal}",
            case: None,
            before: || {
                let mut game = founded(
                    &[(Resource::Metal, 3, 4)],
                    &[(Kind::Labor, 1), (Kind::Metal, 1)],
                );
                game.territories[0].add_extractor(Resource::Metal);
                game
            },
        },
        Example {
            recipe: "build yard",
            command: "{build-yard territory:1}",
            case: None,
            before: || founded(&[], &[(Kind::Labor, 1), (Kind::Metal, 15)]),
        },
        Example {
            recipe: "produce pioneer",
            command: "{produce-pioneer territory:1}",
            case: None,
            before: || {
                founded(
                    &[],
                    &[(Kind::Citizen, 2), (Kind::Metal, 3), (Kind::Energy, 6)],
                )
            },
        },
        Example {
            recipe: "move",
            command: "{move unit:pioneer territory:2}",
            case: Some("moving spends one fuel and leaves the unit not ready"),
            before: || {
                let mut game = beside(true);
                let mut unit = game_model::Unit::new(
                    game_model::UnitId(1),
                    game_model::UnitKind::Pioneer,
                    TerritoryId(1),
                );
                unit.location = game_model::Location::On(TerritoryId(1));
                game.units.push(unit);
                game
            },
        },
        Example {
            recipe: "found by land",
            command: "{found-by-land territory:2}",
            case: Some("the pioneer is consumed and the ground it takes is furnished"),
            before: || {
                let mut game = beside(false);
                game.territories[1].deposits.insert(
                    Resource::Food,
                    game_model::Deposit {
                        capacity: 3,
                        density: 4,
                    },
                );
                game.territories[1].deposits.insert(
                    Resource::Metal,
                    game_model::Deposit {
                        capacity: 3,
                        density: 4,
                    },
                );
                let mut unit = game_model::Unit::new(
                    game_model::UnitId(1),
                    game_model::UnitKind::Pioneer,
                    TerritoryId(1),
                );
                unit.location = game_model::Location::On(TerritoryId(1));
                game.units.push(unit);
                game
            },
        },
        Example {
            recipe: "produce ark",
            command: "{produce-ark territory:1}",
            case: None,
            before: || {
                founded(
                    &[],
                    &[
                        (Kind::Citizen, 2),
                        (Kind::Metal, 3),
                        (Kind::Energy, 12),
                        (Kind::Yard, 1),
                    ],
                )
            },
        },
    ]
}

/// Ground with one resource, and nothing on it.
fn ground(offers: &[(Resource, u32, u32)]) -> Game {
    let mut game = Game::new();
    game.phase = game_model::Phase::Play;
    game.turn = 1;
    let mut place = game_model::Territory::empty(TerritoryId(1), game_model::Biome::Grassland);
    for (resource, capacity, density) in offers {
        place.deposits.insert(
            *resource,
            game_model::Deposit {
                capacity: *capacity,
                density: *density,
            },
        );
    }
    game.territories.push(place);
    game.adjacency.push(Vec::new());
    game
}
